### ISSUE TITLE
feature-request: test release builds in CI

### ISSUE THREAD

**Issue by metachris** [flashbots/mev-boost#475]
It would be great to test mev-boost binaries after building the release builds in https://github.com/flashbots/mev-boost/blob/main/.github/workflows/release.yaml

A good starting point would be to use Ubuntu 20.04, pull the linux binary from the previous step, and run `mev-boost version`

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by ameya-deshmukh** [comment]
@metachris is this still available? Would love to take a shot at this with your guidance😄

**Comment by ralexstokes** [comment]
@ameya-deshmukh it would be great if you want to open a PR for this!

**Comment by ameya-deshmukh** [comment]
@ralexstokes awesome! Will do.

**Comment by matiasADiazPerez** [comment]
Hi team. Is this as simple as to add this job?
``` yaml
 test-binaries:                                                                                       
    needs: release                                                                                     
    runs-on: ubuntu-latest                                                                             
    steps:                                                                                             
      - name: Checkout                                                                                 
        uses: actions/checkout@v3                                                                      
        with:                                                                                          
          fetch-depth: 0                                                                               
      - name: Make directories                                                                         
        run: |                                                                                         
          mkdir -p ./build                                                                             
      - name: Download binaries                                                                        
        uses: actions/download-artifact@v3                                                             
        with:                                                                                          
          name: mev-boost-build                                                                        
          path: ./build                                                                                
      - name: Test binaries                                                                            
        run: |                                                                                         
          cd ./build                                                                                
          tar -xf mev-boost_*_linux_amd64.tar.gz                                                    
          chmod 755  mev-boost                                                                      
          ./mev-boost -version 
```
This also can be accomplished by adding the `Test binaries` step right after [here](https://github.com/flashbots/mev-boost/blob/develop/.github/workflows/release.yaml#L112). But I think is cleaner to do it in another separated job. I can add a PR for this.
